### PR TITLE
Add new feature

### PR DESCRIPTION
**Pull request by pfchen**
- add FBExchangeToken
- add RefreshToken
- add callApi method
- fix undefined name bug
- fix request/response bug
- add grant type

### CODE REVIEW

**Comment by bitinn** [comment]
`callApi` should exists as a separate class and not in this oauth library as it only make use of Guzzle. Also this library focus on **user authentication**, anything beyond that should be in a separate library

**Comment by bitinn** [comment]
Also I would like to know how you are using FBExchangeToken and RefreshToken grant type. Please give me a some code example on how they are used.

When you say _fix a bug on request/response_, you meant oauth client is not using `GuzzleClient` correctly? as in the params in constructor are not used?

It would be great if you have some test case to prove it is the case.

Other things look ok, once you have a working demo we will merge this.

**Comment by bitinn** [comment]
Also hopefully this is a valuable lesson on how to work in open-source environment, as these are the norms.

**Comment by bitinn** [comment]
One more thing, instead of hardcode the google request param in `IdentityProvider`, provide a function to set these params so Google Provider may set them specifically, not just on every provider that implement `IdentityProvider`. A similar example on setting scopes: https://github.com/php-loep/oauth2-client/pull/28/files

**Comment by bitinn** [comment]
a quick note: pending merge.
1. add comment for why guzzle is used in this fashion
2. fix the bug introduced in this commit: https://github.com/pfchen/oauth2-client/commit/fcee2312bd8ec7cc08b3b575bd296e363a86a84e#diff-83d0be78072f8924798f24ae98fd764dR185
3. make sure the client is working by test run
4. (optional) provide some general test case with mockey

**Comment by pfchen** [comment]
test case has been added

**Comment by bitinn** [comment]
great job, let merge this, you can test and feedback

**Comment by bitinn** [comment]
close this as #3 has been merged into branch 2.0, we will keep the local branch as it is.

**Pull request closed without merging**
